/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chatEngine_ChatEngine */

#ifndef _Included_chatEngine_ChatEngine
#define _Included_chatEngine_ChatEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chatEngine_ChatEngine
 * Method:    chat
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_chatEngine_ChatEngine_chat
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
